spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/miniepos}
spring.datasource.username=${DB_USER:miniepos}
spring.datasource.password=${DB_PASSWORD:miniepos}
spring.jpa.hibernate.ddl-auto=update

server.port=8081